swagger: "2.0"
info:
  title: jumia API
  description: Jumia Application API, You can read and test  the APIs from this documentation
  version: "1.0"
host: localhost:80
consumes:
- application/json
- application/xml
produces:
- application/json
- application/xml
- application/gob
paths:
  /customers/v1:
    get:
      tags:
      - customers
      summary: list customers
      description: list customers
      operationId: customers#list
      parameters:
      - name: country
        in: query
        description: country
        required: false
        type: string
        default: all
        enum:
        - all
        - cameroon
        - ethiopia
        - morocco
        - mozambique
        - uganda
      - name: state
        in: query
        description: state
        required: false
        type: string
        default: all
        enum:
        - all
        - Valid
        - NotValid
      - name: sort_direction
        in: query
        required: false
        type: string
        default: desc
        enum:
        - asc
        - desc
      - name: sort_key
        in: query
        required: false
        type: string
        default: CustomerID
        enum:
        - CustomerID
        - CustomerName
        - CustomerPhone
      - name: page_number
        in: query
        required: false
        type: integer
        default: 1
      - name: page_size
        in: query
        required: false
        type: integer
        default: 20
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CustomersListResponseBody'
            required:
            - customers
            - pagination
      schemes:
      - http
  /customers/v1/swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/customers/v1/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  CustomersListResponseBody:
    title: CustomersListResponseBody
    type: object
    properties:
      customers:
        type: array
        items:
          $ref: '#/definitions/ListCustomerRespResponseBody'
        description: events
        example:
        - Country: 2496508963508522800
          CountryCode: 2902339981513357177
          ID: 6410663858109321322
          Name: 7482810282227951744
          Phone: 1480352200424320871
          State: 7632961416346618751
        - Country: 2496508963508522800
          CountryCode: 2902339981513357177
          ID: 6410663858109321322
          Name: 7482810282227951744
          Phone: 1480352200424320871
          State: 7632961416346618751
        - Country: 2496508963508522800
          CountryCode: 2902339981513357177
          ID: 6410663858109321322
          Name: 7482810282227951744
          Phone: 1480352200424320871
          State: 7632961416346618751
      pagination:
        $ref: '#/definitions/PaginationResponseBody'
    example:
      customers:
      - Country: 2496508963508522800
        CountryCode: 2902339981513357177
        ID: 6410663858109321322
        Name: 7482810282227951744
        Phone: 1480352200424320871
        State: 7632961416346618751
      - Country: 2496508963508522800
        CountryCode: 2902339981513357177
        ID: 6410663858109321322
        Name: 7482810282227951744
        Phone: 1480352200424320871
        State: 7632961416346618751
      - Country: 2496508963508522800
        CountryCode: 2902339981513357177
        ID: 6410663858109321322
        Name: 7482810282227951744
        Phone: 1480352200424320871
        State: 7632961416346618751
      pagination:
        current_page: 1
        page_size: 3
        total_count: 33
        total_pages: 11
    required:
    - customers
    - pagination
  ListCustomerRespResponseBody:
    title: ListCustomerRespResponseBody
    type: object
    properties:
      Country:
        type: integer
        description: customer country
        example: 1203459537732876882
        format: int64
      CountryCode:
        type: integer
        description: country code
        example: 302690847954514256
        format: int64
      ID:
        type: integer
        description: customer ID
        example: 1693940815577920245
        format: int64
      Name:
        type: integer
        description: customer name
        example: 3869617325947388408
        format: int64
      Phone:
        type: integer
        description: customer phone
        example: 7187599479213396799
        format: int64
      State:
        type: integer
        description: phone state
        example: 2220215262016194181
        format: int64
    example:
      Country: 3898710109296507508
      CountryCode: 1897589574723350446
      ID: 7725241716640968339
      Name: 4424080603129321661
      Phone: 500625219879757665
      State: 4342933414668473840
    required:
    - ID
    - Name
    - Phone
    - Country
    - State
    - CountryCode
  PaginationResponseBody:
    title: 'Mediatype identifier: pagination; view=default'
    type: object
    properties:
      current_page:
        type: integer
        description: The current page
        example: 1
        format: int64
      page_size:
        type: integer
        description: The current page
        example: 1
        format: int64
      total_count:
        type: integer
        description: Total records count
        example: 33
        format: int64
      total_pages:
        type: integer
        description: The current page
        example: 1
        format: int64
    description: PaginationResponseBody result type (default view)
    example:
      current_page: 1
      page_size: 1
      total_count: 33
      total_pages: 1
